/**
 * Offline fixtures for Project-Centered Research, Samples, Sequence Records, and CRISPR Studies.
 */

import {
  ResearchProject,
  BiologicalSample,
  AnnotatedSequence,
  CrisprObjective,
} from "./project-types";

export const FIXTURE_PROJECTS: ResearchProject[] = [
  {
    project_id: "proj_lactis_nisin",
    name: "Lactococcus lactis Nisin Biosynthetic Cluster & Immunity",
    description:
      "Characterizing natural variants of Nisin lantibiotic operon and NisI lipoprotein immunity in cheese starter isolates.",
    lead_investigator: "Dr. E. Hansen",
    target_organism: "Lactococcus lactis",
    status: "active",
    sample_ids: ["samp_llactis_atcc11454"],
    sequencing_run_ids: ["run_bs_miseq_01"],
    dataset_ids: ["ds_bs_miseq_r1", "ds_bs_miseq_r2"],
    sequence_ids: ["seq_nisin_cluster_ref"],
    amp_job_ids: ["batch-sample-demo-1"],
    crispr_study_ids: ["crispr_nisi_immunity_01"],
    created_at: "2026-10-01T09:00:00Z",
    updated_at: "2026-10-09T20:00:00Z",
  },
  {
    project_id: "proj_enterococcus_as48",
    name: "Enterococcus faecium Enterocin AS-48 Circular Bacteriocin Mining",
    description:
      "Investigating circular bacteriocin AS-48 operon structures in multi-drug resistant clinical Enterococci.",
    lead_investigator: "Dr. M. Alvarez",
    target_organism: "Enterococcus faecium",
    status: "active",
    sample_ids: ["samp_efaecium_e980"],
    sequencing_run_ids: ["run_ont_prome_01"],
    dataset_ids: ["ds_ont_fastq_01", "ds_ont_pod5_01"],
    sequence_ids: ["seq_as48_cluster_ref"],
    amp_job_ids: [],
    crispr_study_ids: ["crispr_as48_transporter_01"],
    created_at: "2026-10-02T10:30:00Z",
    updated_at: "2026-10-08T18:15:00Z",
  },
  {
    project_id: "proj_bacillus_thuricin",
    name: "Bacillus thuringiensis Thuricin CD Sactipeptide System",
    description:
      "Characterizing narrow-spectrum anti-Clostridioides difficile sactipeptide Thuricin CD using PacBio HiFi assemblies.",
    lead_investigator: "Dr. S. O'Connor",
    target_organism: "Bacillus thuringiensis",
    status: "active",
    sample_ids: ["samp_bthuringiensis_hd1"],
    sequencing_run_ids: ["run_pb_revio_01"],
    dataset_ids: ["ds_pb_hifi_01"],
    sequence_ids: ["seq_thuricin_cd_ref"],
    amp_job_ids: [],
    crispr_study_ids: ["crispr_thuricin_sam_01"],
    created_at: "2026-10-03T11:00:00Z",
    updated_at: "2026-10-07T14:45:00Z",
  },
];

export const FIXTURE_SAMPLES: BiologicalSample[] = [
  {
    sample_id: "samp_llactis_atcc11454",
    project_id: "proj_lactis_nisin",
    sample_name: "Lactococcus lactis subsp. lactis ATCC 11454",
    organism: "Lactococcus lactis",
    strain: "ATCC 11454",
    gram_stain: "positive",
    isolation_source: "Dairy Starter Culture",
    collection_date: "2026-09-15",
    sequencing_run_ids: ["run_bs_miseq_01"],
    dataset_ids: ["ds_bs_miseq_r1", "ds_bs_miseq_r2"],
    created_at: "2026-10-01T09:15:00Z",
    metadata: { growth_temp_c: 30, medium: "M17 broth + 0.5% glucose" },
  },
  {
    sample_id: "samp_efaecium_e980",
    project_id: "proj_enterococcus_as48",
    sample_name: "Enterococcus faecium E980",
    organism: "Enterococcus faecium",
    strain: "E980",
    gram_stain: "positive",
    isolation_source: "Human Clinical Isolate",
    collection_date: "2026-08-10",
    sequencing_run_ids: ["run_ont_prome_01"],
    dataset_ids: ["ds_ont_fastq_01", "ds_ont_pod5_01"],
    created_at: "2026-10-02T10:45:00Z",
    metadata: { vancomycin_resistant: true, linezolid_susceptible: true },
  },
  {
    sample_id: "samp_bthuringiensis_hd1",
    project_id: "proj_bacillus_thuricin",
    sample_name: "Bacillus thuringiensis HD1",
    organism: "Bacillus thuringiensis",
    strain: "HD1",
    gram_stain: "positive",
    isolation_source: "Agricultural Soil Isolate",
    collection_date: "2026-07-22",
    sequencing_run_ids: ["run_pb_revio_01"],
    dataset_ids: ["ds_pb_hifi_01"],
    created_at: "2026-10-03T11:20:00Z",
    metadata: { crystal_protein: "Cry1Ac" },
  },
];

export const FIXTURE_SEQUENCES: AnnotatedSequence[] = [
  {
    sequence_id: "seq_nisin_cluster_ref",
    project_id: "proj_lactis_nisin",
    sample_id: "samp_llactis_atcc11454",
    source_dataset_id: "ds_bs_miseq_r1",
    name: "Lactococcus lactis nisin A (nisA) and NisI immunity locus",
    molecule_type: "dna",
    sequence:
      "ATGAATAAAACAAACTTATTATTACATGAAGTAACAGGATCATCATATACTTTTACTAGTACTACAAATGTAAACTCTTTAAGTGCTGGATGTTTAACTGGTTGTTCTACTGGTTGTACAACTGGTTGTTGTGCTACATGTTCTTGTTCTATTCATGTTTCTAAATAAGTTTTAATTTTTTAAGGAGGTGTTTTTATGAAGAAACTCTTAACTCTTACTTTAATTGTAGCACTAATTGTTTCTGGATGTGGAGATAATAGTGAGAAAAGTAGTAAAGATAAAAATTCAAGTGATAAACAAAAAAATAAAGACGATAAATCAAATAAAAATGAAAAAAATGATAAACAAAAAAAGCAAGAGAAGAAGGATAGTGACAAAAATAGTGACAAAGAGAAAGATAGTGACAAAGAAAAAGAGAAAGATAGTGACAAAGAAAAAGAGAAAGATAGTGACAAAGAAAAAGAGAAAGATAGTGACAAA",
    length: 480,
    description:
      "Reference locus encoding lantibiotic Nisin A precursor and NisI lipoprotein immunity factor",
    genomic_coordinates: "NC_007799.1:1820410-1820890",
    reference_version: "v2.1",
    orientation: "5to3",
    annotations: [
      {
        annotation_id: "ann_nisA_cds",
        feature_type: "cds",
        name: "nisA",
        start: 1,
        end: 174,
        strand: "+",
        qualifiers: { gene: "nisA", product: "nisin A precursor peptide" },
        evidence_ids: ["PMID:2839491", "DRAMP:DRAMP00001"],
      },
      {
        annotation_id: "ann_nisA_core",
        feature_type: "core_peptide",
        name: "Nisin A Core Peptide",
        start: 70,
        end: 171,
        strand: "+",
        qualifiers: { cleavage_site: "Arg23-Ile24" },
        evidence_ids: ["PMID:2839491"],
      },
      {
        annotation_id: "ann_nisI_cds",
        feature_type: "immunity_protein",
        name: "nisI",
        start: 195,
        end: 480,
        strand: "+",
        qualifiers: { gene: "nisI", product: "nisin immunity lipoprotein NisI" },
        evidence_ids: ["PMID:8474195"],
      },
      {
        annotation_id: "ann_crispr_target_1",
        feature_type: "crispr_spacer",
        name: "NisI Regulatory Target Region",
        start: 180,
        end: 202,
        strand: "+",
        qualifiers: { pam: "NGG", protospacer: "AAGGAGGTGTTTTTATGAAGAAAC" },
        evidence_ids: ["PMID:29109281"],
      },
    ],
    provenance: { source: "NCBI RefSeq & BaseSpace FASTQ Assembly", verified: true },
    created_at: "2026-10-01T09:30:00Z",
  },
  {
    sequence_id: "seq_as48_cluster_ref",
    project_id: "proj_enterococcus_as48",
    sample_id: "samp_efaecium_e980",
    source_dataset_id: "ds_ont_fastq_01",
    name: "Enterococcus faecium Enterocin AS-48 precursor cluster",
    molecule_type: "dna",
    sequence:
      "ATGAAAAAATTAGCGATTTTGTTGCTTAGTGTTACAGTTTTTGCTGAAGGAAAACCTGAAAAAGTTGTTAGAGGTGCTTGTGCTGGAGTTTGTGCTACTCATTTAACTGTTGTTGCTGGATGTGTTGCTGGTGCTGCTGTTTGTGTTGGTGGTTTTGCTACTTGTGGATGTGCTGTTGGAGGTTTTGCTGCTGGAATTGCAGCTGGTGCTGCTGTTTGTGTTGGAGCTACTGCTGTTGGAGCTGGAGCTGTTGCAGCTGGTGGATTTGCTACTGCTTGTTGTGCTTAA",
    length: 288,
    description: "Reference operon for circular Class IIc bacteriocin Enterocin AS-48",
    genomic_coordinates: "pWVO2:1240-1530",
    reference_version: "v1.4",
    orientation: "5to3",
    annotations: [
      {
        annotation_id: "ann_as48A_cds",
        feature_type: "cds",
        name: "as-48A",
        start: 1,
        end: 288,
        strand: "+",
        qualifiers: { product: "Enterocin AS-48 prepeptide" },
        evidence_ids: ["PMID:9765582", "DRAMP:DRAMP00023"],
      },
      {
        annotation_id: "ann_as48_leader",
        feature_type: "leader_peptide",
        name: "AS-48 Leader",
        start: 1,
        end: 105,
        strand: "+",
        qualifiers: { cleavage: "Ala35-Met36" },
        evidence_ids: ["PMID:9765582"],
      },
    ],
    provenance: { source: "Oxford Nanopore Long-Read MinKNOW & Assembly", verified: true },
    created_at: "2026-10-02T11:00:00Z",
  },
  {
    sequence_id: "seq_thuricin_cd_ref",
    project_id: "proj_bacillus_thuricin",
    sample_id: "samp_bthuringiensis_hd1",
    source_dataset_id: "ds_pb_hifi_01",
    name: "Bacillus thuringiensis Thuricin CD Trn-alpha/beta locus",
    molecule_type: "dna",
    sequence:
      "ATGAATAAAACAAACTTATTATTACATGAAGTAACAGGATCATCATATACTTTTACTAGTACTACAAATGTAAACTCTTTAAGTGCTGGATGTTTAACTGGTTGTTCTACTGGTTGTACAACTGGTTGTTGTGCTACATGTTCTTGTTCTATTCATGTTTCTAAATAAGTTTTAATTTTT",
    length: 180,
    description: "PacBio HiFi consensus locus encoding two-component sactipeptide Thuricin CD",
    genomic_coordinates: "BtHD1_pBMB:41200-41380",
    reference_version: "v1.0",
    orientation: "5to3",
    annotations: [
      {
        annotation_id: "ann_trn_alpha",
        feature_type: "core_peptide",
        name: "Trn-alpha core peptide",
        start: 1,
        end: 90,
        strand: "+",
        qualifiers: { product: "Thuricin CD alpha sactipeptide" },
        evidence_ids: ["PMID:19762534"],
      },
    ],
    provenance: { source: "PacBio Revio SMRT Link HiFi CCS", verified: true },
    created_at: "2026-10-03T11:45:00Z",
  },
];

export const FIXTURE_CRISPR_STUDIES: CrisprObjective[] = [
  {
    study_id: "crispr_nisi_immunity_01",
    project_id: "proj_lactis_nisin",
    sample_id: "samp_llactis_atcc11454",
    title: "NisI Immunity Gene Promoter & Ribosome Binding Site Characterization",
    investigation_purpose:
      "Evaluate natural nucleotide polymorphisms upstream of the nisI immunity lipoprotein gene to understand variations in bacteriocin self-protection thresholds across industrial starter strains. Note: Intended strictly for sequence annotation and variant interpretation; experimental editing instructions excluded.",
    target_gene: "nisI",
    target_sequence_id: "seq_nisin_cluster_ref",
    reference_version: "v2.1",
    target_regions: [
      {
        target_id: "target_nisI_rbs",
        study_id: "crispr_nisi_immunity_01",
        target_name: "nisI Ribosome Binding Site Region",
        locus_tag: "nisI_5UTR",
        sequence_id: "seq_nisin_cluster_ref",
        start_pos: 175,
        end_pos: 205,
        strand: "+",
        target_sequence: "AAGGAGGTGTTTTTATGAAGAAACTCTTAAC",
        pam_motif: "TGG",
        orientation: "5to3",
        annotations: ["RBS Shine-Dalgarno", "Start Codon Met1"],
        published_evidence: [
          { pmid: "8474195", title: "NisI immunity protein protects against external nisin." },
          { pmid: "29109281", title: "Bacteriocin self-resistance gene regulation in lactic acid bacteria." },
        ],
        validation_status: "literature_confirmed",
      },
    ],
    variants: [
      {
        variant_id: "var_nisI_c185T",
        reference_sequence_id: "seq_nisin_cluster_ref",
        position: 185,
        reference_allele: "G",
        alternate_allele: "A",
        variant_type: "snv",
        coordinate_system: "1_based",
        predicted_effect: "Alters Shine-Dalgarno pairing stability (ΔΔG = +1.2 kcal/mol)",
        evidence_citations: ["PMID:29109281"],
        uncertainty_level: "low",
        confidence_score: 0.94,
      },
      {
        variant_id: "var_nisA_hinge",
        reference_sequence_id: "seq_nisin_cluster_ref",
        position: 148,
        reference_allele: "A",
        alternate_allele: "C",
        variant_type: "snv",
        coordinate_system: "1_based",
        predicted_effect: "Nisin Z variant substitution: p.His31Asn",
        evidence_citations: ["PMID:1418703"],
        uncertainty_level: "low",
        confidence_score: 0.98,
      },
    ],
    specificity_considerations:
      "High homology to nisF and nisE ABC transporter promoters; off-target cross-matching requires stringency.",
    experimental_findings_summary:
      "Literature confirms that the Asn31 variant maintains equal antimicrobial activity with improved diffusion.",
    review_status: "approved",
    created_at: "2026-10-01T10:00:00Z",
    updated_at: "2026-10-09T20:00:00Z",
  },
  {
    study_id: "crispr_as48_transporter_01",
    project_id: "proj_enterococcus_as48",
    sample_id: "samp_efaecium_e980",
    title: "Enterocin AS-48 Circularization Domain Variation Analysis",
    investigation_purpose:
      "Document natural sequence diversity across the head-to-tail circularization ligation domain in Enterococcus hospital isolates to assess resistance evolution against membrane pore formation.",
    target_gene: "as-48A",
    target_sequence_id: "seq_as48_cluster_ref",
    reference_version: "v1.4",
    target_regions: [
      {
        target_id: "target_as48_junction",
        study_id: "crispr_as48_transporter_01",
        target_name: "Head-to-tail circularization cleavage site",
        locus_tag: "as-48A_junction",
        sequence_id: "seq_as48_cluster_ref",
        start_pos: 90,
        end_pos: 125,
        strand: "+",
        target_sequence: "GTGCTTGTGCTGGAGTTTGTGCTACTCATTTAACTG",
        pam_motif: "CGG",
        orientation: "5to3",
        annotations: ["Ligation boundary", "Met1-Trp70 circular peptide"],
        published_evidence: [
          { pmid: "9765582", title: "Structure and genetics of circular bacteriocin enterocin AS-48." },
        ],
        validation_status: "literature_confirmed",
      },
    ],
    variants: [
      {
        variant_id: "var_as48_v112C",
        reference_sequence_id: "seq_as48_cluster_ref",
        position: 112,
        reference_allele: "A",
        alternate_allele: "G",
        variant_type: "snv",
        coordinate_system: "1_based",
        predicted_effect: "Conservative substitution: p.Thr38Ala",
        evidence_citations: ["PMID:9765582"],
        uncertainty_level: "low",
        confidence_score: 0.91,
      },
    ],
    specificity_considerations:
      "High GC-islands around ABC transporter genes; specificity filtering required.",
    experimental_findings_summary:
      "Observed in 14 clinical isolates with intact bactericidal potency.",
    review_status: "approved",
    created_at: "2026-10-02T11:15:00Z",
    updated_at: "2026-10-08T18:15:00Z",
  },
];
