/**
 * Offline contract fallback fixtures for Universal Sequencing Integrations.
 *
 * Provides realistic sequencing runs, datasets, connectors, and analysis handoffs
 * matching backend SQLite and platform API contracts.
 */

import {
  ConnectorInfo,
  SequencingConnection,
  SequencingRun,
  SequencingDataset,
  AnalysisHandoffResponse,
  ImportJob,
} from "./sequencing-types";

export const FIXTURE_CONNECTORS: ConnectorInfo[] = [
  {
    connector_id: "illumina_basespace",
    name: "Illumina BaseSpace Sequence Hub",
    vendor: "illumina",
    auth_type: "token",
    description:
      "Synchronizes runs, samples, and demultiplexed FASTQ datasets directly from Illumina BaseSpace Sequence Hub via official v1pre3 API.",
    capabilities: [
      "cloud_sync",
      "run_discovery",
      "sample_tracking",
      "fastq_identification",
      "streaming_download",
      "checksum_preservation",
      "oauth_token_auth",
      "contract_fixtures",
    ],
    supported_file_types: [".fastq.gz", ".fq.gz", ".bam", ".vcf.gz"],
    documentation_url: "https://developer.basespace.illumina.com/",
  },
  {
    connector_id: "oxford_nanopore",
    name: "Oxford Nanopore MinKNOW",
    vendor: "nanopore",
    auth_type: "directory_path",
    description:
      "Integrates with MinKNOW output structures, parses final_summary metrics, separates basecalled reads (fastq_pass) from raw signal (POD5/FAST5).",
    capabilities: [
      "run_discovery",
      "sample_tracking",
      "fastq_ingestion",
      "raw_signal_inventory",
      "final_summary_parsing",
      "checksum_verification",
      "contract_fixtures",
    ],
    supported_file_types: [".fastq", ".fastq.gz", ".fq", ".fq.gz", ".pod5", ".fast5", ".bam", ".cram", ".txt"],
    documentation_url: "https://community.nanoporetech.com/docs/prepare/library_prep_protocols/Guppy-protocol",
  },
  {
    connector_id: "pacbio_smrtlink",
    name: "PacBio SMRT Link",
    vendor: "pacbio",
    auth_type: "api_key",
    description:
      "Connects to Pacific Biosciences SMRT Link servers to isolate high-fidelity consensus reads (HiFi/CCS BAM) from raw continuous long reads.",
    capabilities: [
      "smrtlink_api",
      "run_discovery",
      "hifi_ccs_detection",
      "subread_inventory",
      "checksum_verification",
      "contract_fixtures",
    ],
    supported_file_types: [".bam", ".pbi", ".xml", ".fasta", ".fasta.gz", ".fastq", ".fastq.gz"],
    documentation_url: "https://www.pacb.com/support/software-downloads/",
  },
  {
    connector_id: "local_folder",
    name: "Local & Network Storage Drop",
    vendor: "local",
    auth_type: "directory_path",
    description:
      "Ingests sequencing outputs from allowlisted laboratory storage with path traversal protection, file stability detection, and atomic staging.",
    capabilities: [
      "directory_scanning",
      "file_stability_detection",
      "completion_marker_check",
      "checksum_verification",
      "atomic_import",
    ],
    supported_file_types: [".fastq", ".fastq.gz", ".fq", ".fq.gz", ".fasta", ".fasta.gz", ".bam", ".cram", ".vcf", ".vcf.gz"],
  },
];

export const FIXTURE_CONNECTIONS: SequencingConnection[] = [
  {
    connection_id: "conn_basespace_lab",
    connector_id: "illumina_basespace",
    name: "BaseSpace Sequence Hub (BactroGen Facility)",
    vendor: "illumina",
    status: "connected",
    config_summary: { api_server: "https://api.basespace.illumina.com", use_fixtures: true },
    auto_sync: true,
    sync_interval_seconds: 300,
    last_sync_at: "2026-10-09T21:45:00Z",
    discovered_runs_count: 2,
    discovered_datasets_count: 3,
    error_message: null,
    created_at: "2026-10-01T10:00:00Z",
  },
  {
    connection_id: "conn_nanopore_promethion",
    connector_id: "oxford_nanopore",
    name: "PromethION 2 Solo (Lab P2S-01)",
    vendor: "nanopore",
    status: "connected",
    config_summary: { instrument: "PromethION 2 Solo", use_fixtures: true },
    auto_sync: false,
    sync_interval_seconds: 600,
    last_sync_at: "2026-10-09T20:15:00Z",
    discovered_runs_count: 2,
    discovered_datasets_count: 4,
    error_message: null,
    created_at: "2026-10-02T14:30:00Z",
  },
  {
    connection_id: "conn_pacbio_revio",
    connector_id: "pacbio_smrtlink",
    name: "PacBio Revio SMRT Link (Cluster Alpha)",
    vendor: "pacbio",
    status: "connected",
    config_summary: { server_url: "https://smrtlink.bactrogen.internal:8243", use_fixtures: true },
    auto_sync: false,
    sync_interval_seconds: 300,
    last_sync_at: "2026-10-09T18:00:00Z",
    discovered_runs_count: 2,
    discovered_datasets_count: 3,
    error_message: null,
    created_at: "2026-10-03T09:15:00Z",
  },
  {
    connection_id: "conn_local_drop",
    connector_id: "local_folder",
    name: "Primary Instrument Drop Folder",
    vendor: "local",
    status: "connected",
    config_summary: { directory_path: "/data/sequencing/incoming", require_stability: true },
    auto_sync: true,
    sync_interval_seconds: 120,
    last_sync_at: "2026-10-09T22:00:00Z",
    discovered_runs_count: 1,
    discovered_datasets_count: 2,
    error_message: null,
    created_at: "2026-10-04T11:00:00Z",
  },
];

export const FIXTURE_RUNS: SequencingRun[] = [
  {
    run_id: "run_bs_miseq_01",
    connection_id: "conn_basespace_lab",
    vendor: "illumina",
    external_run_id: "bs_run_20261008_miseq",
    run_name: "261008_M03456_0142_MS0012345-AMP-SCREEN",
    instrument_model: "Illumina MiSeq",
    sequencing_method: "Illumina Sequencing by Synthesis (SBS)",
    project_name: "Bacteriocin_Isolate_Screen_Oct2026",
    sample_count: 12,
    status: "completed",
    started_at: "2026-10-08T08:30:00Z",
    completed_at: "2026-10-08T18:45:00Z",
    dataset_count: 2,
    total_size_bytes: 4823490112,
    source_metadata: { flowcell: "MS0012345", platform: "Illumina" },
    last_synced_at: "2026-10-09T21:45:00Z",
    provenance: { source: "BaseSpace Sequence Hub v1pre3", verified: true },
  },
  {
    run_id: "run_ont_prome_01",
    connection_id: "conn_nanopore_promethion",
    vendor: "nanopore",
    external_run_id: "ont_run_20261007_promethion",
    run_name: "20261007_1430_P2S-01928-A_PAM78901_enterococcus_bacteriocin",
    instrument_model: "PromethION 2 Solo",
    sequencing_method: "Oxford Nanopore Sequencing",
    project_name: "Enterococcus faecium E980",
    sample_count: 1,
    status: "completed",
    started_at: "2026-10-07T14:30:00Z",
    completed_at: "2026-10-08T02:30:00Z",
    dataset_count: 3,
    total_size_bytes: 24890123450,
    source_metadata: { pore_type: "R10.4.1", flow_cell_id: "PAM78901", basecaller: "Dorado 0.5.3 (super-accurate)" },
    last_synced_at: "2026-10-09T20:15:00Z",
    provenance: { source: "MinKNOW final_summary.txt", verified: true },
  },
  {
    run_id: "run_pb_revio_01",
    connection_id: "conn_pacbio_revio",
    vendor: "pacbio",
    external_run_id: "pb_run_revio_20261005",
    run_name: "Run_20261005_Revio_Bacteriocin_Isolates",
    instrument_model: "PacBio Revio",
    sequencing_method: "PacBio HiFi Sequencing",
    project_name: "PacBio Long-Read Genomics",
    sample_count: 4,
    status: "completed",
    started_at: "2026-10-05T08:00:00Z",
    completed_at: "2026-10-06T08:00:00Z",
    dataset_count: 2,
    total_size_bytes: 102242214240,
    source_metadata: { instrument_id: "REVIO-00104", chemistry: "Revio Polymerase v1.0", mean_hifi_qv: 33.4 },
    last_synced_at: "2026-10-09T18:00:00Z",
    provenance: { source: "PacBio SMRT Link REST API", verified: true },
  },
];

export const FIXTURE_DATASETS: SequencingDataset[] = [
  {
    dataset_id: "ds_bs_miseq_r1",
    run_id: "run_bs_miseq_01",
    connection_id: "conn_basespace_lab",
    sample_id: "BAC_Lactis_A1",
    sample_name: "Lactococcus lactis isolate A1",
    file_name: "BAC_Lactis_A1_S1_L001_R1_001.fastq.gz",
    file_path: "AppResults/10023456/Files/BAC_Lactis_A1_S1_L001_R1_001.fastq.gz",
    file_format: "fastq_gz",
    file_size_bytes: 2410940120,
    checksum: "8a7c2b3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef",
    checksum_algorithm: "sha256",
    read_type: "paired_end_R1",
    is_complete: true,
    stability_verified: true,
    import_status: "available",
    local_storage_path: null,
    analysis_eligibility: {
      is_direct_amp_eligible: false,
      requires_assembly_or_orf: true,
      requires_translation: true,
    },
    discovered_at: "2026-10-08T19:00:00Z",
  },
  {
    dataset_id: "ds_bs_miseq_r2",
    run_id: "run_bs_miseq_01",
    connection_id: "conn_basespace_lab",
    sample_id: "BAC_Lactis_A1",
    sample_name: "Lactococcus lactis isolate A1",
    file_name: "BAC_Lactis_A1_S1_L001_R2_001.fastq.gz",
    file_path: "AppResults/10023456/Files/BAC_Lactis_A1_S1_L001_R2_001.fastq.gz",
    file_format: "fastq_gz",
    file_size_bytes: 2412549992,
    checksum: "9b8d3c4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef01",
    checksum_algorithm: "sha256",
    read_type: "paired_end_R2",
    is_complete: true,
    stability_verified: true,
    import_status: "available",
    local_storage_path: null,
    analysis_eligibility: {
      is_direct_amp_eligible: false,
      requires_assembly_or_orf: true,
      requires_translation: true,
    },
    discovered_at: "2026-10-08T19:00:00Z",
  },
  {
    dataset_id: "ds_ont_fastq_01",
    run_id: "run_ont_prome_01",
    connection_id: "conn_nanopore_promethion",
    sample_id: "E_faecium_E980",
    sample_name: "Enterococcus faecium E980",
    file_name: "PAM78901_pass_barcode01_001.fastq.gz",
    file_path: "fastq_pass/barcode01/PAM78901_pass_barcode01_001.fastq.gz",
    file_format: "fastq_gz",
    file_size_bytes: 4120930100,
    checksum: "88a9c1e7a641b9d0e2e132049e7b23f81e053a5c18e9d34e9c70b8a1f4d92e10",
    checksum_algorithm: "sha256",
    read_type: "long_read",
    is_complete: true,
    stability_verified: true,
    import_status: "available",
    local_storage_path: null,
    analysis_eligibility: {
      is_direct_amp_eligible: false,
      requires_assembly_or_orf: true,
      requires_translation: true,
    },
    discovered_at: "2026-10-08T03:00:00Z",
  },
  {
    dataset_id: "ds_ont_pod5_01",
    run_id: "run_ont_prome_01",
    connection_id: "conn_nanopore_promethion",
    sample_id: "E_faecium_E980",
    sample_name: "Enterococcus faecium E980",
    file_name: "PAM78901_output_001.pod5",
    file_path: "pod5/PAM78901_output_001.pod5",
    file_format: "pod5",
    file_size_bytes: 14879072950,
    checksum: "99e128ab8301824ef9381023ba9401284ebf10928348e029318fa9023419bb11",
    checksum_algorithm: "sha256",
    read_type: "raw_signal",
    is_complete: true,
    stability_verified: true,
    import_status: "available",
    local_storage_path: null,
    analysis_eligibility: {
      is_direct_amp_eligible: false,
      requires_basecalling: true,
      requires_assembly_or_orf: true,
      requires_translation: true,
    },
    discovered_at: "2026-10-08T03:00:00Z",
  },
  {
    dataset_id: "ds_pb_hifi_01",
    run_id: "run_pb_revio_01",
    connection_id: "conn_pacbio_revio",
    sample_id: "Bacillus_thuringiensis_HD1",
    sample_name: "Bacillus thuringiensis HD1",
    file_name: "m84012_261005_081432_s1.hifi_reads.bc1001.bam",
    file_path: "outputs/m84012_261005_081432_s1.hifi_reads.bc1001.bam",
    file_format: "bam",
    file_size_bytes: 12840920400,
    checksum: "4a7f23c9108bdae908123456789abcdef0123456789abcdef0123456789abcde",
    checksum_algorithm: "sha256",
    read_type: "hifi_ccs",
    is_complete: true,
    stability_verified: true,
    import_status: "imported",
    local_storage_path: "artifacts/sequencing/imported/m84012_261005_081432_s1.hifi_reads.bc1001.bam",
    analysis_eligibility: {
      is_direct_amp_eligible: false,
      is_hifi: true,
      requires_assembly_or_orf: true,
      requires_translation: true,
    },
    discovered_at: "2026-10-06T09:00:00Z",
  },
];

export const FIXTURE_HANDOFFS: Record<string, AnalysisHandoffResponse> = {
  ds_bs_miseq_r1: {
    dataset_id: "ds_bs_miseq_r1",
    file_format: "fastq_gz",
    data_type: "raw_short_reads",
    direct_amp_eligible: false,
    recommendation:
      "This dataset contains raw short sequencing reads (FASTQ). Prior to bacteriocin screening, reads must undergo quality filtering, de novo assembly, and CDS gene prediction.",
    prerequisite_notice:
      "CRITICAL: Raw nucleotide reads cannot be classified by ampir or amPEPpy. Protein-level translation is mandatory before AMP inference.",
    pipeline_stages: [
      {
        stage_id: "qc",
        name: "Quality Control (FastQC / MultiQC)",
        required: true,
        status: "ready",
        description: "Evaluate per-base sequence quality, adapter contamination, and duplication levels.",
      },
      {
        stage_id: "assembly",
        name: "De Novo Genome Assembly (SPAdes / Unicycler)",
        required: true,
        status: "pending_prerequisite",
        description: "Assemble short paired-end reads into contiguous genomic contigs.",
      },
      {
        stage_id: "gene_calling",
        name: "Prokaryotic ORF Calling (Prodigal)",
        required: true,
        status: "pending_prerequisite",
        description: "Predict open reading frames and coding sequences (CDS) from contigs.",
      },
      {
        stage_id: "translation",
        name: "6-Frame / CDS Translation",
        required: true,
        status: "pending_prerequisite",
        description: "Translate nucleotide coding sequences into candidate amino acid peptide sequences.",
      },
      {
        stage_id: "amp_screening",
        name: "Bacteriocin & AMP Screening (ampir / amPEPpy)",
        required: true,
        status: "pending_prerequisite",
        description: "Execute verified machine-learning antimicrobial peptide prediction models.",
      },
    ],
    extracted_peptides_preview: [],
  },
  ds_pb_hifi_01: {
    dataset_id: "ds_pb_hifi_01",
    file_format: "bam",
    data_type: "raw_long_reads",
    direct_amp_eligible: false,
    recommendation:
      "PacBio HiFi consensus long reads detected (>Q30 accuracy). Gene prediction tools can extract high-confidence bacteriocin ORFs for translation and AMP scoring.",
    prerequisite_notice:
      "HiFi reads must undergo gene calling and peptide translation before AMP prediction.",
    pipeline_stages: [
      {
        stage_id: "qc",
        name: "HiFi Quality Check (SMRT QC)",
        required: true,
        status: "ready",
        description: "Inspect consensus accuracy (QV), insert length distribution, and adapter yield.",
      },
      {
        stage_id: "assembly",
        name: "High-Accuracy Assembly (Hifiasm)",
        required: true,
        status: "pending_prerequisite",
        description: "Assemble HiFi reads into closed circular bacterial contigs.",
      },
      {
        stage_id: "gene_calling",
        name: "Bacteriocin BGC Calling (BAGEL4 / Prodigal)",
        required: true,
        status: "pending_prerequisite",
        description: "Predict precursor peptide genes and modification enzyme clusters.",
      },
      {
        stage_id: "translation",
        name: "Peptide Translation",
        required: true,
        status: "pending_prerequisite",
        description: "Generate 10-100 AA peptide candidates for multi-model scoring.",
      },
      {
        stage_id: "amp_screening",
        name: "Bacteriocin & AMP Screening (ampir / amPEPpy)",
        required: true,
        status: "pending_prerequisite",
        description: "Forward translated candidates directly to B-4 AMP inference workspace.",
      },
    ],
    extracted_peptides_preview: [
      {
        id: "ORF_HD1_bt001",
        sequence: "MKKAAIFLLLLLSVTVFAEGKPEKVVRGACAGVCA",
        length: 35,
        description: "Predicted Class II Bacteriocin core peptide",
        ready_for_amp: true,
      },
      {
        id: "ORF_HD1_bt002",
        sequence: "MKTLTIDNVELSQVTGSSCGCACTHGACGK",
        length: 30,
        description: "Predicted Lantibiotic Precursor",
        ready_for_amp: true,
      },
    ],
  },
};
