#!/usr/bin/env python3
"""Generate the Omnigent MCP declaration for the simulation backend.

Why this exists: Omnigent expands ``${VAR}`` in an MCP server's ``env`` block
but **not** in ``command`` or ``args`` -- its parser documents those as
literals. A committed declaration therefore cannot reference the interpreter
through an environment variable; the paths have to be written out, which makes
them machine-specific. So the real ``bacteriocin-sim.yaml`` is generated here
and gitignored, and only ``bacteriocin-sim.yaml.example`` is committed.

Re-run after moving the repository or changing interpreter.

    python3 integrations/omnigent/simulation/install.py                  # auto-detect
    python3 integrations/omnigent/simulation/install.py --python /path/to/python
    python3 integrations/omnigent/simulation/install.py --bundle <agent dir>
    python3 integrations/omnigent/simulation/install.py --check          # verify only

This mirrors the pattern established by the candidate agent's installer at
``integrations/omnigent/install.py``; see this directory's README for the note
on consolidating both tools into one shared bundle.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
SERVER = HERE / "mcp_server.py"
DEFAULT_BUNDLE = HERE / "agent"
DECLARATION_NAME = "bacteriocin-sim.yaml"

#: Interpreters to try, in order. The server needs the `mcp` SDK and pydantic
#: 2. The repository's own venv is preferred because it is the one the tests
#: run against; Omnigent's bundled interpreter is the pragmatic fallback since
#: it always has the MCP SDK.
_CANDIDATE_PYTHONS = (
    REPO / ".venv" / "bin" / "python",
    Path.home() / ".local/share/uv/tools/omnigent/bin/python",
    Path(sys.executable),
)

TEMPLATE = """\
# GENERATED by integrations/omnigent/simulation/install.py -- do not edit by hand.
# Re-run that script after moving the repository or changing interpreter.
#
# Omnigent expands ${{VAR}} in `env` but NOT in `command` or `args` (its parser
# documents those as literals), so the paths below are resolved absolutes.

name: bacteriocin-sim
transport: stdio
description: >-
  Computational simulation backend of an autonomous bacteriocin-discovery
  system. Predicts a continuous, uncertainty-quantified antimicrobial response
  from a peptide, a target organism and a set of conditions, and reports which
  conditions the prediction is most sensitive to. Simulation-derived only --
  never experimental evidence.

command: "{python}"
args:
  - "{server}"

env:
  PYTHONPATH: "{repo}"
  # stdio is the MCP channel, so logs must stay off stdout.
  BACTERIOCIN_LOG_LEVEL: "WARNING"

# Only these tools reach the model. An explicit list means a tool cannot start
# appearing in the model's context because the server happened to register it.
tools:
  - capabilities
  - get_schema
  - run_experiment
  - run_experiments
  - run_agent
  - describe
  - selftest

# A dose sweep re-runs the ODE at every point and the agent envelope runs every
# spec in the batch, so a planner exploring a grid can legitimately sit well
# past a short default.
timeout: 300
"""


def _imports_dependencies(python: Path) -> bool:
    """Can this interpreter actually import what the server needs?"""
    probe = "import mcp, pydantic"
    try:
        return (
            subprocess.run(
                [str(python), "-c", probe],
                capture_output=True,
                timeout=30,
            ).returncode
            == 0
        )
    except (OSError, subprocess.SubprocessError):
        return False


def find_python(explicit: str | None) -> Path:
    """Pick an interpreter that can import the server's dependencies.

    Deliberately does **not** resolve symlinks. A virtualenv's ``bin/python``
    is a symlink to a base interpreter, and resolving it yields a path that
    runs *without* the venv's site-packages -- so the resolved path fails to
    import ``mcp`` even though the symlink works. Only absoluteness matters,
    because Omnigent treats ``command`` as a literal and a relative path would
    resolve against whatever cwd the server happens to inherit.
    """
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise SystemExit(f"error: {path} is not a file")
        if not path.is_absolute():
            path = Path.cwd() / path
        if not _imports_dependencies(path):
            raise SystemExit(
                f"error: {path} cannot import mcp and pydantic.\n"
                f'  fix: {path} -m pip install "mcp>=1.30" "pydantic>=2.7"'
            )
        return path

    for candidate in _CANDIDATE_PYTHONS:
        if candidate.is_file() and _imports_dependencies(candidate):
            return candidate

    tried = "\n".join(f"  - {p}" for p in _CANDIDATE_PYTHONS)
    raise SystemExit(
        "error: no interpreter found that can import mcp and pydantic.\n"
        f"tried:\n{tried}\n"
        '  fix: uv pip install -e ".[mcp]"  (then re-run)\n'
        "  or:  --python /path/to/an/interpreter"
    )


def render(python: Path, bundle: Path) -> str:
    if not SERVER.is_file():  # pragma: no cover - defensive
        raise SystemExit(f"error: launcher missing at {SERVER}")
    return TEMPLATE.format(python=python, server=SERVER, repo=REPO)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the Omnigent MCP declaration for the simulation backend."
    )
    parser.add_argument(
        "--python",
        default=None,
        help="interpreter to run the server with (default: auto-detect)",
    )
    parser.add_argument(
        "--bundle",
        default=None,
        help=(
            "agent bundle directory to install into; the declaration is written to "
            "<bundle>/tools/mcp/. Point this at the shared bundle to put this tool "
            "and the candidate generator behind one orchestrator."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the declaration is present and current; write nothing",
    )
    args = parser.parse_args(argv)

    bundle = Path(args.bundle).resolve() if args.bundle else DEFAULT_BUNDLE
    target = bundle / "tools" / "mcp" / DECLARATION_NAME

    if args.check:
        if not target.is_file():
            print(f"missing: {target}", file=sys.stderr)
            print(
                "run: python3 integrations/omnigent/simulation/install.py",
                file=sys.stderr,
            )
            return 1
        current = render(find_python(args.python), bundle)
        if target.read_text() != current:
            print(f"stale: {target}", file=sys.stderr)
            print(
                "run: python3 integrations/omnigent/simulation/install.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {target} is present and current")
        return 0

    python = find_python(args.python)
    if not bundle.is_dir():
        raise SystemExit(
            f"error: no agent bundle at {bundle}\n"
            "  pass --bundle <dir> to name one, or create it first"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(python, bundle))

    print(f"wrote {target}")
    print(f"  interpreter: {python}")
    print(f"  server     : {SERVER}")
    print(f"  PYTHONPATH : {REPO}")
    print()
    print(f"run the bundle with:  omnigent run {bundle}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
