#!/usr/bin/env python3
"""Generate every Omnigent MCP declaration for this repository.

Why this exists: Omnigent expands ``${VAR}`` in an MCP server's ``env`` block
but **not** in ``command`` or ``args`` -- its parser documents those as
literals. A committed declaration therefore cannot reference the interpreter
through an environment variable; the paths have to be written out, which makes
them machine-specific. So the real ``tools/mcp/*.yaml`` files are generated
here and gitignored, and only the ``*.yaml.example`` placeholders are
committed.

One installer rather than one per package: the declarations share interpreter
detection and all land in the same bundle, and duplicated copies of this logic
would drift.

Re-run after moving the repository or changing interpreter.

    python3 install.py                              # auto-detect
    python3 install.py --python /path/to/python
    python3 install.py --knowledge-path curated.json
    python3 install.py --check                      # verify, write nothing
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
LAUNCHERS = REPO / "tools" / "launchers"
MCP_DIR = REPO / "tools" / "mcp"

#: Interpreters to try, in order. A server needs the `mcp` SDK and pydantic 2.
#: The repository venv is preferred because it is what the tests run against;
#: Omnigent's bundled interpreter is the fallback since it always has the SDK.
#: Both SDK majors work -- Omnigent 0.16 ships mcp 1.30 (FastMCP), a fresh
#: install resolves 2.x (MCPServer) -- and both servers detect which is present.
_CANDIDATE_PYTHONS = (
    REPO / ".venv" / "bin" / "python",
    Path.home() / ".local/share/uv/tools/omnigent/bin/python",
    Path(sys.executable),
)

_HEADER = """\
# GENERATED by install.py -- do not edit by hand.
# Re-run that script after moving the repository or changing interpreter.
#
# Omnigent expands ${VAR} in `env` but NOT in `command` or `args` (its parser
# documents those as literals), so the paths below are resolved absolutes.
"""


class Server:
    """One MCP declaration to generate."""

    def __init__(
        self,
        *,
        name: str,
        launcher: str,
        pythonpath: Path | tuple[Path, ...],
        description: str,
        tools: list[str],
        timeout: int,
    ) -> None:
        self.name = name
        self.launcher = LAUNCHERS / launcher
        # One path, or several (the knowledge server needs its package, the shared schemas and the
        # contract package); joined the way PYTHONPATH always is.
        self.pythonpath = os.pathsep.join(str(p) for p in ((pythonpath,) if isinstance(pythonpath, Path) else pythonpath))
        self.description = description
        self.tools = tools
        self.timeout = timeout

    @property
    def target(self) -> Path:
        return MCP_DIR / f"{self.name}.yaml"

    def render(self, python: Path, extra_env: str = "") -> str:
        tools = "\n".join(f"  - {t}" for t in self.tools)
        return (
            f"{_HEADER}\n"
            f"name: {self.name}\n"
            f"transport: stdio\n"
            f"description: >-\n"
            f"  {self.description}\n"
            f"\n"
            f'command: "{python}"\n'
            f"args:\n"
            f'  - "{self.launcher}"\n'
            f"\n"
            f"env:\n"
            f'  PYTHONPATH: "{self.pythonpath}"\n'
            f"  # stdio is the MCP channel, so logs must stay off stdout.\n"
            f'  BACTERIOCIN_LOG_LEVEL: "WARNING"\n'
            f"{extra_env}"
            f"\n"
            f"# Only these tools reach the model.\n"
            f"tools:\n{tools}\n"
            f"\n"
            f"timeout: {self.timeout}\n"
        )


SERVERS = [
    Server(
        name="critic",
        launcher="critic.py",
        pythonpath=REPO,
        description=(
            "Scientific critic / safety agent. Reviews claims BEFORE the loop accepts\n"
            "  them: checks that conclusions follow from results, that simulated evidence\n"
            "  is never described as experimentally validated, that coverage, controls and\n"
            "  uncertainty support the wording, and routes work back when they do not.\n"
            "  Does not approve by default."
        ),
        tools=["review_claims", "run_agent", "describe", "get_schema"],
        # Pure rule evaluation over the submitted payload; no I/O, no model.
        timeout=60,
    ),
    Server(
        name="literature",
        launcher="literature.py",
        pythonpath=REPO,
        description=(
            "Literature & Evidence Agent. Retrieves bounded literature metadata and\n"
            "  abstracts, then conservatively extracts experimental conditions,\n"
            "  measurements, provenance, missing variables, and contradictions.\n"
            "  Literature-derived claims only -- never a candidate decision."
        ),
        tools=["literature_evidence"],
        # Europe PMC calls are explicitly bounded by the tool request. The
        # process ceiling leaves room for the maximum supported source timeout.
        timeout=90,
    ),
    Server(
        name="candidates",
        launcher="candidates.py",
        pythonpath=REPO,
        description=(
            "Candidate Generation & Design Agent. Proposes ranked candidates and\n"
            "  falsifiable hypotheses. Proposals only -- never experimental evidence."
        ),
        tools=["generate_candidates", "describe_agent"],
        # Scoring is pure computation over a small pool, so calls return in
        # milliseconds. A low ceiling surfaces a hung subprocess quickly.
        timeout=60,
    ),
    Server(
        name="runner",
        launcher="runner.py",
        pythonpath=REPO,
        description=(
            "Computational simulation experiment backend. Predicts a continuous,\n"
            "  uncertainty-quantified antimicrobial response and reports which\n"
            "  conditions it is most sensitive to. Simulation-derived only."
        ),
        tools=[
            "capabilities",
            "get_schema",
            "run_experiment",
            "run_experiments",
            "run_agent",
            "describe",
            "selftest",
        ],
        # A dose sweep re-runs the ODE at every point and a batch runs every
        # spec, so a grid search can legitimately sit past a short default.
        timeout=300,
    ),
    Server(
        name="knowledge",
        launcher="knowledge.py",
        pythonpath=REPO,
        description=(
            "Knowledge / Research-State Agent. The persistent, append-only,\n"
            "  reconstructable scientific state: candidate and hypothesis registries\n"
            "  with full status history, experiment and result history, known variable\n"
            "  relationships, open questions and uncertainties. Record-keeping only --\n"
            "  nothing is validated."
        ),
        tools=[
            "initialize_research_state",
            "register_candidates",
            "record_experiment_plan",
            "register_evidence",
            "update_research_state",
            "reject_candidate",
            "close_open_question",
            "get_candidate_history",
            "get_hypothesis_history",
            "get_experiment_history",
            "get_open_questions",
            "summarize_research_state",
            "get_state_at_iteration",
            "verify_state_integrity",
        ],
        # Pure bookkeeping over a local log; milliseconds per call.
        timeout=60,
    ),
]


def _imports_dependencies(python: Path) -> bool:
    """Can this interpreter import what the servers need?"""
    try:
        return (
            subprocess.run(
                [str(python), "-c", "import mcp, pydantic"],
                capture_output=True,
                timeout=30,
            ).returncode
            == 0
        )
    except (OSError, subprocess.SubprocessError):
        return False


def find_python(explicit: str | None) -> Path:
    """Pick an interpreter that can import the servers' dependencies.

    Deliberately does **not** resolve symlinks. A virtualenv's ``bin/python``
    is a symlink to a base interpreter, and resolving it yields a path that
    runs *without* the venv's site-packages -- so the resolved path fails to
    import ``mcp`` even though the symlink works. Only absoluteness matters,
    because Omnigent treats ``command`` as a literal and a relative path would
    resolve against whatever cwd the server happens to inherit.
    """
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise SystemExit(f"error: {path} is not a file")
        if not path.is_absolute():
            path = Path.cwd() / path
        if not _imports_dependencies(path):
            raise SystemExit(
                f"error: {path} cannot import mcp and pydantic.\n"
                f'  fix: {path} -m pip install "mcp>=1.30" "pydantic>=2.7"'
            )
        return path

    for candidate in _CANDIDATE_PYTHONS:
        if candidate.is_file() and _imports_dependencies(candidate):
            return candidate

    tried = "\n".join(f"  - {p}" for p in _CANDIDATE_PYTHONS)
    raise SystemExit(
        "error: no interpreter found that can import mcp and pydantic.\n"
        f"tried:\n{tried}\n"
        '  fix: uv pip install -e ".[mcp]"  (then re-run)\n'
        "  or:  --python /path/to/an/interpreter"
    )


def _knowledge_env(knowledge_path: str | None) -> str:
    """The candidate server's optional curated-dataset override."""
    if not knowledge_path:
        return (
            "  # Point this at a curated dataset to replace the seed data:\n"
            "  # BACTERIOCIN_KNOWLEDGE_PATH: /path/to/bactibase_export.json\n"
        )
    resolved = Path(knowledge_path).resolve()
    if not resolved.is_file():
        raise SystemExit(f"error: knowledge file not found: {resolved}")
    return f'  BACTERIOCIN_KNOWLEDGE_PATH: "{resolved}"\n'


def _rendered(python: Path, knowledge_path: str | None) -> dict[Path, str]:
    out: dict[Path, str] = {}
    for server in SERVERS:
        if not server.launcher.is_file():
            raise SystemExit(f"error: launcher missing at {server.launcher}")
        extra = _knowledge_env(knowledge_path) if server.name == "candidates" else ""
        out[server.target] = server.render(python, extra)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the Omnigent MCP declarations for this repository."
    )
    parser.add_argument(
        "--python", default=None, help="interpreter to run the servers with"
    )
    parser.add_argument(
        "--knowledge-path",
        default=None,
        help="curated knowledge JSON for the candidate agent, instead of the seed",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the declarations are present and current; write nothing",
    )
    args = parser.parse_args(argv)

    python = find_python(args.python)
    rendered = _rendered(python, args.knowledge_path)

    if args.check:
        stale = [
            path
            for path, text in rendered.items()
            if not path.is_file() or path.read_text() != text
        ]
        if stale:
            for path in stale:
                state = "missing" if not path.is_file() else "stale"
                print(f"{state}: {path}", file=sys.stderr)
            print("run: python3 install.py", file=sys.stderr)
            return 1
        print(f"ok: {len(rendered)} declaration(s) present and current")
        return 0

    MCP_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in rendered.items():
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO)}")

    print(f"\n  interpreter: {python}")
    print("\nrun the lab with:  omnigent run .")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
