"""The knowledge agent fed by the REAL candidate agent, Result Analysis Agent and simulator.

Nothing here is hand-assembled analysis JSON: candidates come from ``CandidateGenerationAgent``,
verdicts from ``analyze_result`` (comparing each result with all earlier ones), and one test uses
results generated by ``bacteriocin_sim``. The state must absorb their real output shapes.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from bacteriocin_lab.agents.analysis import analyze_result
from bacteriocin_lab.agents.candidate import CandidateGenerationAgent
from bacteriocin_lab.agents.knowledge import (
    JsonFileStateStore,
    ResearchStateManager,
    get_hypothesis_history,
    get_open_questions,
    summarize_current_state,
)
from bacteriocin_lab.tests.knowledge.knowledge_helpers import clock

SPEC_FILE = Path(__file__).parents[2] / "evaluation" / "examples" / "simulator" / "spec_nisin_listeria.json"
DENSITY_NEGATIVE = {"variable": "target_cell_density", "direction": "negative"}


def raw_result(
    rid: str, inhibition: float, *, density: float, ph: float, candidate: str, hypothesis: str
) -> dict:
    return {
        "result_id": rid,
        "experiment_id": f"exp_{rid}",
        "candidate_id": candidate,
        "hypothesis_id": hypothesis,
        "conditions": {
            "bacteriocin_concentration": 10.0,
            "target_cell_density": density,
            "ph": ph,
            "temperature_c": 37.0,
        },
        "measurement": {
            "predicted_inhibition_fraction": inhibition,
            "predicted_survival_fraction": round(1 - inhibition, 4),
            "uncertainty": 0.03,
        },
        "evidence_type": "simulation-derived",
        "model_version": "sim/1.0",
    }


@pytest.fixture
def campaign(tmp_path):
    cands = (
        CandidateGenerationAgent()
        .run_envelope(
            {
                "target": {"organism": "Listeria monocytogenes", "gram": "positive"},
                "constraints": {"max_candidates": 2},
            }
        )
        .model_dump(mode="json")
    )
    top = cands["decision"]["candidates"][0]
    cid, hid = top["candidate_id"], top["hypotheses"][0]["hypothesis_id"]
    mgr = ResearchStateManager(JsonFileStateStore(tmp_path / "state"), clock=clock)
    mgr.initialize(
        {"goal": "does target density reduce inhibition?", "target": "Listeria monocytogenes"}
    )
    mgr.register_candidates(cands)
    return mgr, cid, hid, [], []


def turn(mgr, cid, hid, results, snapshots, n, inhibition, density, ph):
    r = raw_result(f"r{n}", inhibition, density=density, ph=ph, candidate=cid, hypothesis=hid)
    mgr.record_experiment_plan(
        {
            "experiment_id": r["experiment_id"],
            "candidate_id": cid,
            "hypothesis_id": hid,
            "conditions": r["conditions"],
        }
    )
    env = analyze_result(
        {
            "result": r,
            "previous_results": list(results),
            "hypothesis": {"hypothesis_id": hid, "expected_relationship": DENSITY_NEGATIVE},
        }
    )
    updated = mgr.update_state(env, result=r)
    results.append(r)
    snapshots.append(mgr.state())
    return env, updated


def test_real_candidate_output_is_registered_with_hypotheses_and_rankings(campaign):
    mgr, cid, hid, _, _ = campaign
    state = mgr.state()
    assert (
        len(state.candidates) == 2
        and len(state.hypotheses) >= 2
        and state.hypotheses[hid].candidate_id == cid
    )
    assert all(
        c.validation_status == "unvalidated" and c.status == "proposed"
        for c in state.candidates.values()
    )
    assert state.rankings and [r["rank"] for r in state.rankings[-1].ranking] == [1, 2]
    assert state.hypotheses[hid].falsified_if  # the candidate agent's falsification clause survives
    assert "candidate-generation/0.1.0" in state.model_versions


def test_support_then_weakening_from_real_analyses_keeps_both_in_the_history(campaign):
    mgr, cid, hid, results, snaps = campaign
    # pH 7: inhibition falls as density rises -> the hypothesis is supported
    turn(mgr, cid, hid, results, snaps, 1, 0.86, 1e6, 7.0)
    env2, _ = turn(mgr, cid, hid, results, snaps, 2, 0.43, 1e8, 7.0)
    assert env2["decision"]["hypothesis_status"] == "supported"
    assert mgr.state().hypotheses[hid].status == "supported"
    assert mgr.state().relationships[f"{cid}::target_cell_density"].relationship == "negative"
    # pH 8: the opposite trend appears in a controlled pair -> the hypothesis is weakened
    turn(mgr, cid, hid, results, snaps, 3, 0.30, 1e6, 8.0)
    env4, up4 = turn(mgr, cid, hid, results, snaps, 4, 0.80, 1e8, 8.0)
    assert env4["decision"]["hypothesis_status"] == "weakened"

    hyp = mgr.state().hypotheses[hid]
    assert hyp.status in ("weakened", "rejected")
    path = [(c.previous_status, c.new_status) for c in hyp.status_history]
    assert (
        path[:2] == [(None, "open"), ("open", "supported")] and path[2][0] == "supported"
    )  # both states, in order
    (t,) = up4.hypothesis_transitions
    assert t["previous_status"] == "supported" and t["new_status"] in ("weakened", "rejected")
    assert "experiment:exp_r4" in t["triggered_by"] and any(
        x.startswith("finding:") for x in t["triggered_by"]
    )

    # The same variable now has two different known relationships over time, both preserved.
    rel = mgr.state().relationships[f"{cid}::target_cell_density"]
    assert [(c.previous_status, c.new_status) for c in rel.history] == [
        (None, "negative"),
        ("negative", "positive"),
    ]
    assert any(q["kind"] == "relationship_reversal" for q in get_open_questions(mgr.state()))
    assert mgr.verify_integrity() == []


def test_a_real_inconclusive_first_result_leaves_the_hypothesis_untouched(campaign):
    mgr, cid, hid, results, snaps = campaign
    env, up = turn(
        mgr, cid, hid, results, snaps, 1, 0.86, 1e6, 7.0
    )  # a single point: nothing controlled to compare
    assert env["decision"]["hypothesis_status"] == "inconclusive"
    hyp = mgr.state().hypotheses[hid]
    assert hyp.status == "open" and up.hypothesis_transitions == [] and hyp.n_inconclusive == 1
    qs = {q["kind"] for q in get_open_questions(mgr.state(), include_derived=False)}
    assert "resolve_variable" in qs  # the analysis's suggested experiment became a tracked question


def test_the_whole_real_campaign_reconstructs_turn_by_turn(campaign):
    mgr, cid, hid, results, snaps = campaign
    for n, (inh, dens, ph) in enumerate(
        [(0.86, 1e6, 7.0), (0.43, 1e8, 7.0), (0.30, 1e6, 8.0), (0.80, 1e8, 8.0)], start=1
    ):
        turn(mgr, cid, hid, results, snaps, n, inh, dens, ph)
    assert (
        mgr.state()
        == ResearchStateManager(JsonFileStateStore(mgr.store.directory), clock=clock).state()
    )
    for n, snap in enumerate(snaps, start=1):
        assert mgr.state_at_iteration(n).model_dump_json() == snap.model_dump_json()
    summary = summarize_current_state(mgr.state())
    assert summary["iteration"] == 5 and summary["counts"]["results"] == 4
    assert "Nothing here is experimentally validated" in summary["provenance"]
    history = get_hypothesis_history(mgr.state(), hid)
    assert history["hypothesis"]["epistemic_status"] == "inferred hypothesis, not a fact"
    assert any(
        e["derived_from_evidence_type"] == "simulation-derived" for e in history["evidence"]
    )  # analysis evidence is linked


def test_real_simulator_results_flow_through_analysis_into_the_state(tmp_path):
    api = pytest.importorskip("bacteriocin_lab.agents.simulator.api")
    spec = json.loads(SPEC_FILE.read_text())

    def run(eid: str, density: float) -> dict:
        s = json.loads(json.dumps(spec))
        s["experiment_id"], s["hypothesis_id"] = eid, "hyp-0001"
        s["conditions"]["bacteriocin_concentration"]["value"] = 0.3
        s["conditions"]["target_cell_density"]["value"] = density
        return api.run_experiment(s).model_dump(mode="json")

    mgr = ResearchStateManager(JsonFileStateStore(tmp_path / "s"), clock=clock)
    mgr.initialize({"goal": "density effect on nisin vs Listeria"})
    hyp = {
        "hypothesis_id": "hyp-0001",
        "statement": "Higher density reduces inhibition",
        "candidate_id": "cand-nisin-a",
        "expected_relationship": DENSITY_NEGATIVE,
    }
    prior: list[dict] = []
    for eid, density in (("exp-lo", 1e6), ("exp-hi", 1e8)):
        res = run(eid, density)
        mgr.record_experiment_plan(
            {
                "experiment_id": eid,
                "candidate_id": "cand-nisin-a",
                "hypothesis_id": "hyp-0001",
                "target": spec["target"],
            }
        )
        env = analyze_result({"result": res, "previous_results": prior, "hypothesis": hyp})
        mgr.update_state(env, result=res, hypothesis=hyp)
        prior.append(res)
    state = mgr.state()
    assert set(state.results) == {r["result_id"] for r in prior}
    assert state.results[prior[0]["result_id"]].result["measurement"][
        "ci95_inhibition_fraction"
    ]  # the simulator's raw result is kept verbatim
    assert state.results[prior[0]["result_id"]].model_version == prior[0]["model_version"]
    assert all(r.evidence_type == "simulation-derived" for r in state.results.values())
    assert (
        state.hypotheses["hyp-0001"].status in ("open", "supported", "weakened", "rejected")
        and len(state.findings) == 2
    )
    assert mgr.verify_integrity() == []
