#!/usr/bin/env python3
"""Generate the Omnigent MCP server declaration with resolved absolute paths.

Why this exists: Omnigent expands ``${VAR}`` references in an MCP server's
``env`` block, but **not** in ``command`` or ``args`` -- its own parser
documents those as literals. So a portable bundle cannot reference the
interpreter or the script through environment variables; the paths have to be
written out. This script resolves them and writes
``agent/tools/mcp/bacteriocin.yaml``.

Re-run it after moving the repository or changing interpreter.

    python3 integrations/omnigent/install.py                 # auto-detect
    python3 integrations/omnigent/install.py --python /path/to/python
    python3 integrations/omnigent/install.py --knowledge-path /path/to/curated.json
    python3 integrations/omnigent/install.py --check         # verify, write nothing
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
TARGET = HERE / "agent" / "tools" / "mcp" / "bacteriocin.yaml"
SERVER = HERE / "mcp_server.py"

#: Interpreters to try, in order. The MCP server needs the `mcp` SDK and
#: pydantic 2; Omnigent's own tool environment has both, which makes it the
#: pragmatic default when the user's python does not.
_CANDIDATE_PYTHONS = (
    Path.home() / ".local/share/uv/tools/omnigent/bin/python",
    Path(sys.executable),
)

TEMPLATE = """\
# GENERATED by integrations/omnigent/install.py -- do not edit by hand.
# Re-run that script after moving the repository or changing interpreter.
#
# Omnigent expands ${{VAR}} in `env` but NOT in `command` or `args` (its parser
# documents those as literals), so the paths below are resolved absolutes.

name: bacteriocin
transport: stdio
description: >
  Candidate Generation & Design Agent of an autonomous bacteriocin-discovery
  system. Proposes ranked candidates and falsifiable hypotheses. Proposals
  only -- never experimental evidence.

command: "{python}"
args:
  - "{server}"

env:
  PYTHONPATH: "{src}"
  # stdio is the MCP channel, so logs must stay off stdout.
  BACTERIOCIN_LOG_LEVEL: "WARNING"
{knowledge}
# Only these tools reach the model.
tools:
  - generate_candidates
  - describe_agent

# Scoring is pure computation over a small pool, so calls return in
# milliseconds. A low ceiling surfaces a hung subprocess quickly.
timeout: 60
"""


def find_python(explicit: str | None) -> Path:
    """Pick an interpreter that can actually import the server's dependencies.

    Deliberately does **not** call ``Path.resolve()`` on the interpreter. A
    virtualenv's ``bin/python`` is a symlink to a base interpreter, and
    resolving it yields a path that runs *without* the venv's site-packages --
    so the resolved path fails to import ``mcp`` even though the symlink works.
    Only ``is_absolute`` matters here, and these candidates already are.
    """
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise SystemExit(f"error: {path} is not a file")
        if not path.is_absolute():
            # Omnigent treats `command` as a literal, so a relative path would
            # resolve against whatever cwd the server happens to have.
            path = Path.cwd() / path
        verify_python(path, fatal=True)
        return path

    for candidate in _CANDIDATE_PYTHONS:
        if candidate.is_file() and verify_python(candidate, fatal=False):
            return candidate

    raise SystemExit(
        "error: no interpreter found with both `mcp` and `pydantic` installed.\n"
        "  Install them into your python:  pip install 'mcp>=1.0' 'pydantic>=2.5'\n"
        "  then re-run with:               --python $(which python3)"
    )


def verify_python(python: Path, *, fatal: bool) -> bool:
    """Check that ``python`` can import the MCP SDK, pydantic, and the agent."""
    probe = (
        "import mcp, pydantic; "
        "from bacteriocin_discovery.candidate_agent import generate_candidates; "
        "print('ok')"
    )
    result = subprocess.run(
        [str(python), "-c", probe],
        capture_output=True,
        text=True,
        env={"PYTHONPATH": str(REPO / "src"), "PATH": "/usr/bin:/bin"},
        timeout=60,
        check=False,
    )
    ok = result.returncode == 0 and "ok" in result.stdout
    if not ok and fatal:
        raise SystemExit(
            f"error: {python} cannot run the MCP server.\n{result.stderr.strip()}"
        )
    return ok


def render(python: Path, knowledge_path: str | None) -> str:
    knowledge = ""
    if knowledge_path:
        resolved = Path(knowledge_path).resolve()
        if not resolved.is_file():
            raise SystemExit(f"error: knowledge file not found: {resolved}")
        knowledge = f'  BACTERIOCIN_KNOWLEDGE_PATH: "{resolved}"\n'
    else:
        knowledge = (
            "  # Point this at a curated dataset to replace the UNVERIFIED seed data:\n"
            "  # BACTERIOCIN_KNOWLEDGE_PATH: /path/to/bactibase_export.json\n"
        )
    return TEMPLATE.format(
        python=python, server=SERVER, src=REPO / "src", knowledge=knowledge
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python", help="Interpreter to run the MCP server with.")
    parser.add_argument("--knowledge-path", help="Curated knowledge JSON to use instead of the seed.")
    parser.add_argument("--check", action="store_true", help="Verify only; write nothing.")
    args = parser.parse_args()

    python = find_python(args.python)
    print(f"interpreter : {python}")
    print(f"server      : {SERVER}")
    print(f"PYTHONPATH  : {REPO / 'src'}")

    content = render(python, args.knowledge_path)

    if args.check:
        if not TARGET.is_file():
            print(f"\nCHECK FAILED: {TARGET} does not exist. Run without --check.")
            return 1
        current = TARGET.read_text(encoding="utf-8")
        if current.strip() == content.strip():
            print(f"\nCHECK OK: {TARGET.relative_to(REPO)} is up to date.")
            return 0
        print(f"\nCHECK FAILED: {TARGET.relative_to(REPO)} is stale. Re-run without --check.")
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"\nwrote {TARGET.relative_to(REPO)}")

    if shutil.which("omnigent"):
        print("\nNext:")
        print(f"  omnigent run {(HERE / 'agent').relative_to(Path.cwd()) if Path.cwd() in HERE.parents or Path.cwd() == REPO else HERE / 'agent'} \\")
        print('    -p "Propose 3 candidates against Listeria monocytogenes at pH 6-7.5, 1e8 CFU/mL."')
    else:
        print("\nomnigent not on PATH; add ~/.local/bin to PATH to run the agent.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
